### ISSUE TITLE
Typo "hisres" instead of "hires"

### ISSUE THREAD

**Issue by pjotrek-b** [ablwr/illustrations#1]
I think the "Cables Table: Digital Video" PNG image has a typo in its filename:
https://github.com/ablwr/media-id-posters/blob/master/cables_table_digital_white_hisres.png

Shouldn't it be "white_hires.png"?

:)

**Comment by ablwr** [comment]
Haha how did I miss this Issue? You are right!

**Comment by pjotrek-b** [comment]
:smile:

_ISO 86743 Certified Typo-Finder_

**Comment by ablwr** [comment]
I pushed straight to `master`. 😎
